swagger: "2.0"
info:
  description: Python, Flask and Connexion server exposing GStreamer udp stream video composition functionality. SurfaceStreams enables merging of video streams based on alpha keying. Clients register with this server to provide their video stream and receive a merged stream from all other clients back.
  version: "1.0.0"
  title: SurfaceStreams Server ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /server-config:
    get:
      operationId: handlers.server_config.read_all
      tags:
        - server-config
      summary: Read the current SurfaceStreams server config
      description: Read the current SurfaceStreams server config
      responses:
        200:
          description: Successfully read server config
          schema:
            properties:
              merged-stream-width:
                type: integer
              merged-stream-height:
                type: integer

    put:
      operationId: handlers.server_config.update
      tags:
      - server-config
      summary: Update the current SurfaceStreams server config
      description: Update the current SurfaceStreams server config
      parameters:
      - name: config
        in: body
        schema:
          type: object
          properties:
            merged-stream-width:
              type: integer
            merged-stream-height:
              type: integer
      responses:
        200:
          description: Successfully updated SurfaceStreams server config

  /clients:
    get:
      operationId: handlers.clients.read_all
      tags:
        - clients
      summary: Read the entire list of clients
      description: Read the list of clients
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of clients to get from clients
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering clients
          required: false
      responses:
        200:
          description: Successfully read clients list operation
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                uuid:
                  type: string
                ip:
                  type: string
                video_src_port:
                  type: integer
                video_sink_port:
                  type: integer
                video_protocol:
                  type: string
                created_datetime:
                  type: string
                tuio_sink_port:
                  type: integer

    post:
      operationId: handlers.clients.create
      tags:
        - clients
      summary: Create a client and add it to the clients list
      description: Create a new client in the clients list (-1 for int, and "" for string means parameter is unset)
      parameters:
        - name: client
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of client to create
                default: "client"
              video_src_port:
                type: integer
                description: Port for incoming client stream
                default: 5001
              video_sink_port:
                type: integer
                description: Port for outgoing merged stream (-1 means set dynamically)
                default: -1
              video_protocol:
                type: string
                description: Streaming protocol used for incoming and outgoing video stream
                default: "jpeg"
              tuio_sink_port:
                type: integer
                description: Port used for merged tuio stream (-1 means set dynamically)
                default: -1
      responses:
        201:
          description: Successfully created client in list
          schema:
            properties:
              name:
                type: string
              uuid:
                type: string
              video_src_port:
                type: integer
              ip:
                type: string
              video_sink_port:
                type: integer
              video_protocol:
                type: string
              tuio_sink_port:
                type: integer
              created_datetime:
                type: string

  /clients/{uuid}:
    get:
      operationId: handlers.clients.read_one
      tags:
        - clients
      summary: Read one client from the clients list
      description: Read one client from the clients list
      parameters:
        - name: uuid
          in: path
          description: uuid of the client to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read client from clients list operation
          schema:
            properties:
              name:
                type: string
              uuid:
                type: string
              video_src_port:
                type: integer
              ip:
                type: string
              video_sink_port:
                type: integer
              video_protocol:
                type: string
              created_datetime:
                type: string

    put:
      operationId: handlers.clients.update
      tags:
        - clients
      summary: Update a client in the clients list
      description: Update a client in the clients list
      parameters:
        - name: uuid
          in: path
          description: uuid of the client to update in the list (-1 for int, and "" for string means parameter is unset)
          type: string
          required: True
        - name: client
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
                default: ""
              video_src_port:
                type: integer
                default: -1
              video_sink_port:
                type: integer
                default: -1
              tuio_sink_port:
                type: integer
                default: -1
      responses:
        200:
          description: Successfully updated client in clients list

    delete:
      operationId: handlers.clients.delete
      tags:
        - clients
      summary: Delete a client from the clients list
      description: Delete a client
      parameters:
        - name: uuid
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted a client from clients list

  /images:
    get:
      operationId: handlers.images.read_all
      tags:
        - images
      summary: Read the entire list of images
      description: Read the list of images
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of images to get from images
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering images
          required: false
      responses:
        200:
          description: Successfully read images list operation
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                uuid:
                  type: string
                created_datetime:
                  type: string

    post:
      operationId: handlers.images.create
      tags:
        - images
      summary: Create a image and add it to the images list
      description: Create a new image in the images list (-1 for int, and "" for string means parameter is unset)
      parameters:
        - name: image
          in: body
          description: Image to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of image to create
                default: "image"
      responses:
        201:
          description: Successfully created image in list
          schema:
            properties:
              name:
                type: string
              uuid:
                type: string
              created_datetime:
                type: string

  /images/{uuid}:
    get:
      operationId: handlers.images.read
      tags:
        - images
      summary: Read the entire list of images
      description: Read the list of images
      parameters:
        - name: uuid
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully read images list operation
          schema:
            type: file

    put:
      operationId: handlers.images.fill
      tags:
        - images
      summary: Fill a image and add it to the images list
      description: Fill an image in the images list
      parameters:
        - name: uuid
          in: path
          type: string
          required: True
        - name: data
          in: formData
          description: data to fill
          required: True
          type: file
      responses:
        200:
          description: Successfully created image in list

    delete:
      operationId: handlers.images.delete
      tags:
        - images
      summary: Delete an image from the images list
      description: Delete an image
      parameters:
        - name: uuid
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted an image from images list